 #!/usr/bin/env python3

"""
dynamic.py

Iterative bottom-up dynamic programming solution to longest common
subsequence problem.

Usage:
    python3 dynamic.py
"""

__author__ = "Maksim Yegorov"
__date__ = "2016-04-28 Thu 02:39 PM"

from profilers import log_recursion, time_and_space_profiler
from profilers import registry #, MEMLOG
from generate_string import strgen
import sys

sys.setrecursionlimit(10000)

@time_and_space_profiler(repeat = 1) #, stream = MEMLOG)
def lcs_bottomup(seq1, seq2):
    """Calls helper function to calculate an LCS.

    Args:
        seq1 (string):  a random string sequence generated by
                        generate_string.strgen()
        seq2 (string):  another random string sequence like seq1
    Returns:
        LCS table

    """
    # reset registry
    registry['_lcs_bottomup'] = 0

    len1 = len(seq1)
    len2 = len(seq2)

    # store length of LCS[i,j] in lcs_table
    lcs_table = [[0 for j in range(len2+1)] \
                    for i in range(len1+1)]
    _lcs_bottomup(seq1, seq2, len1+1, len2+1,
                    lcs_table)
    return lcs_table

@log_recursion
def _lcs_bottomup(seq1, seq2, i, j, lcs_table):
    """Iterative bottom-up dynamic programming solution to
    LCS problem. See CLRS p.394.

    Args:
        seq1 (string):  a string sequence generated by
                            generate_string.strgen()
        seq2 (string):  another random string sequence
                            like seq1
        i (int):        number of rows in LCS table
                            (=len(seq1) + 1)
        j (int):        number of columns in LCS table
                            (=len(seq2) + 1)
        lcs_table (2D list):   a matrix of LCS length for
                                [i-1, j-1] prefix
    Returns:
        None:    modifies in place LCS length table
    """

    for row in range(1, i):
        for col in range(1, j):
            if seq1[row-1] == seq2[col-1]:
                lcs_table[row][col] = \
                    lcs_table[row-1][col-1] + 1
            elif lcs_table[row-1][col] \
                    >= lcs_table[row][col-1]:
                lcs_table[row][col] = \
                        lcs_table[row-1][col]
            else:
                lcs_table[row][col] = \
                        lcs_table[row][col-1]
def size_lcs(lcs_table):
    """Returns length of maximum common subsequence.

    Args:
        lcs_table (2D list):   a matrix of LCS length for
                                [i, j] prefix
    Returns:
        length (int):           LCS length
    """
    return lcs_table[-1][-1]

@time_and_space_profiler(repeat = 1) #, stream = MEMLOG)
def reconstruct_lcs_dynamic(lcs_table, lcs_length, seq1, seq2):
    """Calls helper function to reconstruct
    one possible LCS based on saved LCS lengths table.

    Args:
        seq1 (string):  a string sequence generated by
                            generate_string.strgen()
        seq2 (string):  another random string sequence like seq1
        lcs_length (int):   length of LCS
        lcs_table (2D list):   a matrix of LCS length for
                                [i, j] prefix
    Returns:
        lcs (string):   an LCS
    """
    # reset registry
    registry['_reconstruct_lcs_dynamic'] = 0

    i = len(seq1)
    if i < 1:
        return ""
    else:
        j = len(seq2)
        lcs_arr = _reconstruct_lcs_dynamic(lcs_table, seq1, seq2,
                lcs_length-1, i, j, [None] * lcs_length)
        lcs = "".join(lcs_arr)
        return lcs

@log_recursion
def _reconstruct_lcs_dynamic(lcs_table, seq1, seq2, char, i, j,\
        lcs_arr):

    # if already done with LCS, return
    if (char < 0 or i < 1 or j < 1):
        return lcs_arr
    # else consider general case
    else:
        prev, up, left = (lcs_table[i-1][j-1],
                            lcs_table[i-1][j],
                            lcs_table[i][j-1])

        if (seq1[i-1] == seq2[j-1]):
            lcs_arr[char] = seq1[i-1]
            return _reconstruct_lcs_dynamic(lcs_table, seq1, seq2,
                    char-1, i-1, j-1, lcs_arr)
        elif (up >= left):
            return _reconstruct_lcs_dynamic(lcs_table, seq1,
                    seq2, char, i-1, j, lcs_arr)
        else:
            return _reconstruct_lcs_dynamic(lcs_table, seq1,
                    seq2, char, i, j-1, lcs_arr)


if __name__ == "__main__":
    """Tests and top-level logic go here."""

    sequence_1 = strgen(['a','b','c'], 100)
    sequence_2 = strgen(['a','b','c'], 100)
    #sequence_1 = "abcbdab"
    #sequence_2 = "bdcaba"
    #print("seq1: %s" %sequence_1)
    #print("seq2: %s" %sequence_2)

    name, elapsed, memlog, lcs_table = \
            lcs_bottomup(sequence_1, sequence_2)
    lcs_length = size_lcs(lcs_table)
    recursion_depth = registry['_lcs_bottomup']
    print("LCS length: %d" %lcs_length)


    #for row in lcs_table:
    #    print(row)
    #print()

    name, elapsed, memlog, lcs = reconstruct_lcs_dynamic(lcs_table, lcs_length, sequence_1, sequence_2)
    print("\n(an) LCS: %s" %lcs)
    print("[%0.7fs] %s(%d) -> %d recursive calls"
            %(elapsed, name, lcs_length, \
                    registry['_reconstruct_lcs_dynamic']))

    # test reconstruction match
    name, elapsed, memlog, lcs_table = \
            lcs_bottomup("","")
    lcs_length = size_lcs(lcs_table)
    waste, waste, memlog, lcs = reconstruct_lcs_dynamic(lcs_table, lcs_length, "","")
    assert lcs == ""
    name, elapsed, memlog, lcs_table = \
            lcs_bottomup("","123")
    lcs_length = size_lcs(lcs_table)
    waste, waste, memlog, lcs = reconstruct_lcs_dynamic(lcs_table, lcs_length, "", "123")
    assert lcs == ""
    name, elapsed, memlog, lcs_table = \
            lcs_bottomup("123","")
    lcs_length = size_lcs(lcs_table)
    waste, waste, memlog, lcs = reconstruct_lcs_dynamic(lcs_table, lcs_length, "123", "")
    assert lcs == ""
    name, elapsed, memlog, lcs_table = \
            lcs_bottomup("123","abc")
    lcs_length = size_lcs(lcs_table)
    waste, waste, memlog, lcs = reconstruct_lcs_dynamic(lcs_table, lcs_length, "123", "abc")
    assert lcs == ""
    name, elapsed, memlog, lcs_table = \
            lcs_bottomup("123","123")
    lcs_length = size_lcs(lcs_table)
    waste, waste, memlog, lcs = reconstruct_lcs_dynamic(lcs_table, lcs_length, "123", "123")
    assert lcs == "123"
    name, elapsed, memlog, lcs_table = \
            lcs_bottomup("bbcaba","cbbbaab")
    lcs_length = size_lcs(lcs_table)
    waste, waste, memlog, lcs = reconstruct_lcs_dynamic(lcs_table, lcs_length, "bbcaba", "cbbbaab")
    assert lcs == "bbab"
